config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  
  
  resources :articles
  
  
  get 'signup', to: 'users#new'

  resources :users, except: [:new]
  
  
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  resources :categories, except: [:destroy]
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 3, maximum: 300}
  validates :user_id, presence: true
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  
  
  ## refers to rake routes, for actions to take
#    articles GET    /articles(.:format)          articles#index
#             POST   /articles(.:format)          articles#create
# new_article GET    /articles/new(.:format)      articles#new
# edit_article GET    /articles/:id/edit(.:format) articles#edit
#     article GET    /articles/:id(.:format)      articles#show
#             PATCH  /articles/:id(.:format)      articles#update
#             PUT    /articles/:id(.:format)      articles#update
  ##          DELETE /articles/:id(.:format)      articles#destroy
  
  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end
  
  def edit
    # @article = Article.find(params[:id])
  end
  
  def create
    # debugger
    # render plain: params[:article].inspect
    
    @article = Article.new(article_params)
    # @article.user = User.first
    @article.user = current_user
    # @article.save
    
    # # redirect_to articles_show(@article)   --WRONG
    #   redirect_to article_path(@article)
      
    if @article.save
      # do something
      
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
      
    else
      render 'new'
    end
  end
  
  
  
  def update
    # @article = Article.find(params[:id])

    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
      
    else
      render 'edit'
    end
    
  end
  
  def show
    # @article = Article.find(params[:id])
  end
  
  def destroy
    # @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
      
  end
  
  
  ## move code to method !!
  private
    def set_article
      @article = Article.find(params[:id])
    end
    
    def article_params
      # params.require(:article).permit(:title, :description)
      params.require(:article).permit(:title, :description, category_ids: [])
    end
  
    def require_same_user
      # if current_user != @article.user 
      #   give admin full access:
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
      
    end
  
end

app/views/articles/_article.html.erb
<!--Taken from index.html.erb-->
<!-- @articles.each do |arti|  <<<<<  ruby tag will cause error:   -->
<% obj.each do |arti| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to arti.title, article_path(arti) %>
        </div>

        <div class="article-body">
          <%= truncate(arti.description, length: 100) %>

          <!--adding styling-->
          <div class="article-meta-details">
            <small>Created by: <%= arti.user.username if arti.user%>,
                              <%= time_ago_in_words(arti.created_at) %> ago,
                  Last updated: <%= time_ago_in_words(arti.updated_at) %> ago
            </small>
          </div>
          
        </div>
        
        <% if arti.categories.any? %>
        <p>Categories: <%= render arti.categories %></p>
        <% end %>
        
        <!--< if logged_in? && current_user == arti.user %>-->
        <% if logged_in? && (current_user == arti.user || current_user.admin?) %>
        
        <div class="article-actions">
          <%= link_to 'Edit this article', edit_article_path(arti), class: "btn btn-xs btn-primary" %> 
          <%= link_to 'Delete this article', article_path(arti), method: :delete, 
                                        data: {confirm: "Are you sure want to delete the article?"}, 
                                        class: "btn btn-xs btn-danger" %> 
        </div>
        <% end %>
        
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<!--see partial _errors.html.erb-->
<!--_form.html.erb-->
<%= render 'shared/errors', obj_1: @article %>

<!-- if @article.errors.any? %>-->
<!--  <div class="row">-->
<!--    <div class="col-xs-8 col-xs-offset-2">  -->
                          <!--to the right 2-col-->
<!--      <div class="panel panel-danger">-->
<!--        <div class="panel-heading">-->
<!--          <h2 class="panel-title">-->
<!--             pluralize(@article.errors.count, "error") %>-->
<!--            prohibited this article from being saved:-->
<!--          </h2>-->
  <!--<h2  The following errors prevented the article from getting created-->
  
<!--          <div class="panel-body">-->
<!--            <ul>-->
<!--               @article.errors.full_messages.each do |msg| %>-->
<!--                <li> msg %></li>-->
<!--               end %>-->
<!--            </ul>-->
          
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!-- end %>-->


<!--IMPORTANT !!-->
<!--this form_for == the RUBY form builder , will conflict with BOOTSTRAP <form class=.....-->
<!--dont put another <form class=... under RUBY form_for-->
<div class='row'>
  <div class='col-xs-12'>
    
    
    <!--add: class=form-horizontal -->
    <!--form_for @article do |f| -->
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">        
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %> 
        </div>
      </div>
      
      
      
      <!--with <p tag works-->
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">        
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>


      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>


      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    
    <% end %>
    
    <div class="col-xs-4 col-xs-offset-4">
      <!--link_to 'Back to articles listing',articles_path-->
      [ <%= link_to 'Cancel request and return to article listing',articles_path %> ]
    </div>

  </div>
</div>

app/views/articles/_form_html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from getting created</h2>
  <ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  
<% end %>


<!--IMPORTANT !!-->
<!--this form_for == the RUBY form builder , will conflict with BOOTSTRAP <form class=.....-->
<!--dont put another <form class=... under RUBY form_for-->

<%= form_for @article do |f| %>
  <!--need to instantiate @article in controller-->
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %> 
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %> 
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back to articles listing',articles_path %>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<!--<h1>Listing of all articles</h1>-->
<!--<p>-->
<!--   link_to "Create new article", new_article_path %>-->
<!--</p>-->

<!--<table>-->
<!--  <tr>-->
<!--    <th>Title</th>-->
<!--    <th>Description</th>-->
<!--  </tr>-->
  
<!--   @articles.each do |arti| %>-->
<!--  <tr>-->
<!--    <td> arti.title %></td>-->
<!--    <td> arti.description %></td>-->
<!--    <td> link_to 'Edit', edit_article_path(arti) %></td> -->
<!--    <td> link_to 'Show', article_path(arti) %></td>-->
<!--    <td> link_to 'Delete', article_path(arti), method: :delete, data: {confirm: "Are you sure?"} %></td>-->
<!--  </tr>-->
<!--   end %>-->
  
<!--</table>-->


<h1 align="center">Listing of all articles</h1>

<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %> 

<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<!--<h1>Create an article</h1>-->
<h1 align="center">Create an article</h1>

<!--if its shared then 'shared/form'-->
<%= render 'form' %>

app/views/articles/show.html.erb
<!--<h1>Showing selected article</h1>-->

<!--<p>-->
<!--  Title: <= @article.title %>-->
<!--</p>-->

<h2 align="center">Title: <%= @article.title %></h2>


<!--<p>-->
<!--  Description:  @article.description %>-->
<!--</p>-->

<div class="well col-xs-8 col-xs-offset-2">
  
  <% if @article.user %>
  
  <!--FROM users\index.html-->
  <!--but change u5  to @article.user-->
  <ul class="listing">
    <div class="row center">
                
      <!--<div class="well col-md-4 col-md-offset-4">-->
      <div class="col-md-4 col-md-offset-4">
        
        <!--Add created by-->
        <li>Created by:</li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user)  %></li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user)  %>
        </li>
        <li><small>
          <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
          </small></li>
      </div>
    </div>
    
  </ul>
  <% end %>
  
  <h4 class="center descr"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  
  
  <!-- Lect 148   shortcut than do ||    -->
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>

  
  
  <div class="article-actions">
    
    <!--< if logged_in? && current_user == @article.user %>-->
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    
    <%= link_to 'Edit this article', edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
    <%= link_to 'Delete this article', article_path(@article), method: :delete, 
                                      data: {confirm: "Are you sure want to delete the article?"}, 
                                      class: "btn btn-xs btn-danger" %> 
    
    <% end %>
    
    <%= link_to 'View all articles', articles_path, class: "btn btn-xs btn-success" %>
    
<!-- link_to 'Edit this article', edit_article_path(@article) %> |-->
<!-- link_to 'Back to articles listing', articles_path %>-->
  </div>
</div>