config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  
  
  resources :articles
  
  
  get 'signup', to: 'users#new'

  resources :users, except: [:new]
  
  
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  resources :categories, except: [:destroy]
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :article_categories
  has_many :articles, through: :article_categories
  
  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  
  
  def index
    # @categories = Category.all
    @categories = Category.paginate(page: params[:page], per_page: 5)  ## run rake test >> ensure code not broke
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(cate_params)
    if @category.save
      flash.now[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
  ## edit form submission will be  handle by update action
  ## edit form submission will be  handle by update action
  ## edit form submission will be  handle by update action
  def edit 
    @category = Category.find(params[:id])

  end
  
  def update
    # debugger
    
    @category = Category.find(params[:id])
    if @category.update(cate_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end

  end
  
  

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)

  end
  
  private
  def cate_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !logged_in?  || (logged_in? and !current_user.admin?)
      # flash.now[:danger] = "Only admins can perform that action"   >> cause it to hide message !!
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
  
end

app/views/categories/_category.html.erb
<span class="badge">
  <%= link_to category.name, category_path(category) %> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj_1: @category %>



    
    
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">        
          <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %> 
        </div>
      </div>
      
      
      
      
      

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    
    <% end %>
    
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to 'Cancel request and return to article listing',articles_path %> ]
    </div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing all Categories</h1>

<div align="center">
<%= will_paginate %>

<% @categories.each do |cate| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li class="article-title">
          <%= link_to "#{cate.name}", category_path(cate) %>
        </li>
        <li><small><%= pluralize(cate.articles.count, "article") %></small></li>
      </div>
    </div>
  </ul>
<% end %>
<%= will_paginate %>

</div>

<!--1) <Error:            NEED to initiate @cate in index inside controller -->
<!--CreateCategoriesTest#test_get_new_category_form_and_create_category:-->
<!--ActionView::Template::Error: undefined method `each' for nil:NilClass-->
<!--    app/views/categories/index.html.erb:2:in `_app_views_categories_index_html_erb___3783389707110546292_54418620'-->
<!--    test/integration/create_categories_test.rb:13:in `block (2 levels) in <class:CreateCategoriesTest>'-->
<!--    test/integration/create_categories_test.rb:12:in `block in <class:CreateCategoriesTest>'-->
    

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>

<div align="center">
  
  
  <% if logged_in? and current_user.admin? %>
    <div class="row">
    <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
    </div>
  <% end %>

  <%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', obj: @category_articles %> 

<div align="center">
  <%= will_paginate @category_articles %>
</div>